version: "3"
services: 
  express:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
    depends_on: 
      - mongo-db
  
  mongo-db:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd!
    volumes: 
      - mongo-data:/data/db
  
  redis:
    image: redis
    

volumes: 
  mongo-data: