version: "3"
services: 
  express:
    build:
      context: .
      args: 
        NODE_ENV: production
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
      - NODE_ENV=production
    command: node index.js
    
        