version: "3"
services: 
  express:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./.:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - MONGO_USER=mongo-user
      - MONGO_PW=Passw0rd!
      - SECRET=secret
    command: npm run dev
  mongo-db:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd!
  